#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/radius-sync-daemon.py

start_service() {
    config_load radius_sync
    config_get_bool enabled main enabled 0

    if [ "$enabled" -eq 1 ]; then
        procd_open_instance
        procd_set_param command python3 "$PROG"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
    fi
}

service_triggers() {
    procd_add_reload_trigger "radius_sync"
}
