#!/bin/sh
# /www/cgi-bin/radius_mac_data
# Lightweight endpoint: fast reading with 0% CPU overhead

printf "Content-Type: application/json\r\n"
printf "Cache-Control: no-cache\r\n"
printf "Access-Control-Allow-Origin: *\r\n\r\n"

JSON_FILE="/tmp/horus_radius.json"

if [ -f "$JSON_FILE" ] && [ -s "$JSON_FILE" ]; then
    cat "$JSON_FILE"
else
    printf '{"data":[]}'
fi
