#!/bin/sh /etc/rc.common
# HAMax Init Service - Horus AirMax Protocol
START=99
STOP=10
USE_PROCD=1

start_service() {
    local enabled
    enabled=$(uci -q get hamax.settings.enabled)
    [ "$enabled" = "1" ] || return 0

    logger -t hamax "Starting HAMax service"
    /usr/bin/hamax enable
}

stop_service() {
    logger -t hamax "Stopping HAMax service"
    /usr/bin/hamax disable
}

reload_service() {
    stop_service
    sleep 1
    start_service
}

service_triggers() {
    procd_add_reload_trigger "hamax"
    procd_add_reload_trigger "wireless"
}
