#!/bin/sh /etc/rc.common
START=10

boot() {
    BASE_MAC=$(strings /dev/mtd5 | grep -o 'base_mac=[^ ]*' | head -n 1 | cut -d= -f2)
    if [ -n "$BASE_MAC" ]; then
        ip link set dev eth0 address "$BASE_MAC" 2>/dev/null
    fi
}
